name: Build Mod Library

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        add-to-path: true

    - name: Compile with NDK
      run: |
        cd app/src/main/jni
        ndk-build

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-so-library
        path: app/src/main/libs/
        
